FIND_PATH(SSVUTILSJSON_INCLUDE_DIR
  NAMES SSVUtilsJson/SSVUtilsJson.h
  PATH_SUFFIXES include/
  PATHS "${PROJECT_SOURCE_DIR}/../SSVUtilsJson/"
  "${PROJECT_SOURCE_DIR}/extlibs/SSVUtilsJson/"
  ${SSVUTILSJSON_ROOT}
  $ENV{SSVUTILSJSON_ROOT}
  /usr/local/
  /usr/
  /sw/       
  /opt/local/
  /opt/csw/  
  /opt/
)

message("\nFound SSVUtilsJson include at: ${SSVUTILSJSON_INCLUDE_DIR}.\n")

FIND_LIBRARY(SSVUTILSJSON_LIBRARY
  NAMES SSVUtilsJson SSVUtilsJson-s
  PATH_SUFFIXES lib/ lib64/
  PATHS "${PROJECT_SOURCE_DIR}/../SSVUtilsJson/"
  "${PROJECT_SOURCE_DIR}/extlibs/SSVUtilsJson/"
  ${SSVUTILSJSON_ROOT}
  $ENV{SSVUTILSJSON_ROOT}
  /usr/local/
  /usr/
  /sw/       
  /opt/local/
  /opt/csw/  
  /opt/
)

message("\nFound SSVUtilsJson library at: ${SSVUTILSJSON_LIBRARY}.\n")

IF(SSVUTILSJSON_LIBRARY AND SSVUTILSJSON_INCLUDE_DIR)
  SET(SSVUTILSJSON_LIBRARIES ${SSVUTILSJSON_LIBRARY})
  SET(SSVUTILSJSON_FOUND TRUE)
ELSE(SSVUTILSJSON_LIBRARY AND SSVUTILSJSON_INCLUDE_DIR)
  SET(SSVUTILSJSON_FOUND FALSE)
ENDIF(SSVUTILSJSON_LIBRARY AND SSVUTILSJSON_INCLUDE_DIR)

IF(SSVUTILSJSON_FOUND)
  MESSAGE(STATUS "Found SSVUtilsJson in ${SSVUTILSJSON_INCLUDE_DIR}")
ELSE(SSVUTILSJSON_FOUND)
  IF(SSVUTILSJSON_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find SSVUtilsJson library")
  ENDIF(SSVUTILSJSON_FIND_REQUIRED)
ENDIF(SSVUTILSJSON_FOUND)

MARK_AS_ADVANCED(
  SSVUTILSJSON_LIBRARY
  SSVUTILSJSON_INCLUDE_DIR
)
